server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/items {
        proxy_pass http://app:3000/items;
        include /etc/nginx/proxy_params;
    }

    location /api/items/ {
        proxy_pass http://app:3000/items;
        include /etc/nginx/proxy_params;
    }

    location /api/stats {
        proxy_pass http://app:3000/stats;

        proxy_cache stats_cache;
        proxy_cache_valid 200 30s;

        add_header X-Cache-Status $upstream_cache_status;

        include /etc/nginx/proxy_params;
    }

    # Healthcheck nginx (nie przechodzi przez backend)
    location /nginx-health {
        return 200 "nginx ok\n";
        add_header Content-Type text/plain;
    }
}